const coffees=[
{name:'Guji Shakiso',country:'Ethiopia',region:'Guji',elevation:'1,900–2,100m',process:'Natural',roast:'Light',notes:'Blueberry • Peach • Jasmine',price:18,weight:'12 oz'},
{name:'Huila La Plata',country:'Colombia',region:'Huila',elevation:'1,700–1,950m',process:'Washed',roast:'Medium',notes:'Caramel • Orange • Cocoa',price:17,weight:'12 oz'},
{name:'Huehuetenango',country:'Guatemala',region:'Huehuetenango',elevation:'1,600–1,900m',process:'Washed',roast:'Medium',notes:'Brown Sugar • Almond • Cocoa',price:18,weight:'12 oz'},
{name:'Nyeri AA',country:'Kenya',region:'Nyeri',elevation:'1,700–1,900m',process:'Washed',roast:'Light',notes:'Blackcurrant • Grapefruit • Cane Sugar',price:20,weight:'12 oz'},
{name:'Tarrazú',country:'Costa Rica',region:'San José',elevation:'1,500–1,800m',process:'Honey',roast:'Light',notes:'Red Apple • Honey • Citrus',price:19,weight:'12 oz'},
{name:'Mantiqueira',country:'Brazil',region:'Minas Gerais',elevation:'1,100–1,300m',process:'Natural',roast:'Medium',notes:'Milk Chocolate • Hazelnut • Cherry',price:16,weight:'12 oz'}];
const grid=document.querySelector('#coffeeGrid'),search=document.querySelector('#search'),origin=document.querySelector('#origin'),processEl=document.querySelector('#process'),roast=document.querySelector('#roast'),empty=document.querySelector('#empty');
function options(el,key){[...new Set(coffees.map(c=>c[key]))].sort().forEach(v=>el.insertAdjacentHTML('beforeend',`<option>${v}</option>`))}options(origin,'country');options(processEl,'process');options(roast,'roast');
function render(){const q=search.value.trim().toLowerCase();const list=coffees.filter(c=>(!q||Object.values(c).join(' ').toLowerCase().includes(q))&&(!origin.value||c.country===origin.value)&&(!processEl.value||c.process===processEl.value)&&(!roast.value||c.roast===roast.value));grid.innerHTML=list.map(c=>`<article class="card"><span class="country">${c.country.toUpperCase()} • ${c.region.toUpperCase()}</span><h3>${c.name}</h3><div class="meta"><div><b>Elevation</b>${c.elevation}</div><div><b>Process</b>${c.process}</div><div><b>Roast</b>${c.roast}</div><div><b>Weight</b>${c.weight}</div></div><div class="notes">${c.notes}</div><div class="price"><strong>$${c.price}</strong><span class="pill">ROASTED FRESH</span></div></article>`).join('');empty.hidden=list.length!==0} [search,origin,processEl,roast].forEach(x=>x.addEventListener('input',render));document.querySelector('#year').textContent=new Date().getFullYear();render();
